### ISSUE TITLE
Add Linters

### ISSUE THREAD

**Issue by FarokhC** [Kushal-C/OrganicFoodStore#2]
We should add linters to improve the quality of the code by following some sort of standards and catch some errors. 

I was thinking we should use [`eslint`](/eslint/eslint), [`prettier`](/prettier/prettier) and/or [`stylelint`](/stylelint/stylelint).

**Comment by Kushal-C** [comment]
If you are using VSCode, please use Prettier

**Comment by vikr01** [comment]
@Kushal-C `prettier` should be included as a node module, however `eslint` is still needed to detect errors and be a more configurable linter.

I recommended using everything @FarokhC mentioned along with `lint-staged`, `husky`, `eslint-config-airbnb`, and `eslint-config-prettier`. [electron-react-boilerplate](https://github.com/chentsulin/electron-react-boilerplate/tree/v0.16.0) has great linting configurations if you need an idea.
